name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Required to fetch all branches and tags for a complete mirror

      - name: Push to GitLab
        env:
          ACCESS_TOKEN_GITLAB: ${{ secrets.KTEST_GITLAB }}
          ACCESS_TOKEN_GIT_SE: ${{ secrets.KTEST_GIT_SE }}
          MIRROR_URL: "gitlab.com/shinhyungyang/ktest.git"
        run: |
          # Add the GitLab remote using the oauth2 user and your access token
          git remote add gitlab https://oauth2:${ACCESS_TOKEN_GITLAB}@${MIRROR_URL}
          
          # Force push all branches and tags to the GitLab repository
          git push gitlab main --force

      - name: Push to Git SE
        env:
          ACCESS_TOKEN: ${{ secrets.KTEST_GIT_SE }}
          MIRROR_URL: "git.se.informatik.uni-kiel.de/shinhyungyang/ktest.git"
        run: |
          # Add the GitLab remote using the oauth2 user and your access token
          git remote add git-se https://oauth2:${ACCESS_TOKEN_GIT_SE}@${MIRROR_URL}
          
          # Force push all branches and tags to the GitLab repository
          git push git-se main --force
